FROM mcr.microsoft.com/vscode/devcontainers/cpp:0-ubuntu-22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    clang-format \
    build-essential \
    libstdc++-12-dev \
    libasound2-dev \
    libx11-dev \
    libxcomposite-dev \
    libxcursor-dev \
    libxext-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxrender-dev \
    libfreetype6-dev \
    libfontconfig1-dev \
    libcurl4-openssl-dev \
    libgtk-3-dev \
    libwebkit2gtk-4.0-dev
